### ISSUE TITLE
Possibility to leave markers spiderfied when clicked

### ISSUE THREAD

**Issue by paulrohrbeck** [jawj/OverlappingMarkerSpiderfier#1]
Hey there,

first of all: thanks for this great script, really helped me a lot! :-)

Maybe you can help me: Is there a way I could leave the markers spiderfied once I click one of them? Because in your version the user has to go back each time and click on the first marker to see all of the markers again...
Do you know what I mean?

Paul

**Comment by elpbatista** [comment]
hello George,
"keepSpiderfied: true" does not work for me, I've tried with "keepSpiderfied: 1" and nothing changes.
I need all markers visible at the same time. Can you help me, please.

**Comment by jawj** [comment]
@elpbatista, perhaps you're expecting some different functionality to what `keepSpiderfied` is designed to provide? When you use `keepSpiderfied`, markers stay spiderfied as long as the user clicks only on those markers. When the user clicks elsewhere, the markers collapse again. Keeping markers constantly spiderfied is not compatible with how the library works — please see various other closed issues.

**Comment by elpbatista** [comment]
@jawj You are right, I was expecting something different. Thanks for your answer!
