### ISSUE TITLE
leg height

### ISSUE THREAD

**Issue by neshala** [jawj/OverlappingMarkerSpiderfier#102]
Is it possible to configure height of leg, i saw legWeight , but i really would like to make bigger space between many markers located on same lat and lng?

Problem:
![height](https://cloud.githubusercontent.com/assets/1878392/10890129/88568100-8196-11e5-9d44-ac7d202ab6a9.png)

**Comment by jawj** [comment]
You can experiment with these additional undocumented properties (defaults in brackets):

circleFootSeparation (23)
spiralFootSeparation (26)
spiralLengthStart (11)
spiralLengthFactor (4)

**Comment by neshala** [comment]
Thanks a lot, i got some pretty interesting results using following config:
circleSpiralSwitchover: "Infinity",
circleFootSeparation: 50

Thanks a lot for help, really appreciate it.

![circle](https://cloud.githubusercontent.com/assets/1878392/10895237/6cf2a89a-81b3-11e5-8ffa-02324424dec4.png)
