### ISSUE TITLE
z-Indices reset

### ISSUE THREAD

**Issue by sawittwer** [jawj/OverlappingMarkerSpiderfier#117]
Hello,

I'm setting the markers zIndex and Labels before using OverlappingMarkerSpiderfier.addMarker()

`marker.setLabel('' + (markerLocation[marker.getPosition()]));
marker.setOptions({
    zIndex: markerLocation[marker.getPosition()]
});`

This works well until I spiderfy and then unspiderfy my overlapping markers (see screenshots).

![1](https://cloud.githubusercontent.com/assets/17765184/20274855/73410b1c-aa96-11e6-8e55-5a957771e004.png)
![2](https://cloud.githubusercontent.com/assets/17765184/20274857/73419082-aa96-11e6-8308-1ebfb4d13c79.png)
![3](https://cloud.githubusercontent.com/assets/17765184/20274856/73412f66-aa96-11e6-9d45-29f66f5d4d6c.png)

I did see that

> Some earlier versions had broken support for z-indices [...]

Is this referring to similar behavior or am I doing something wrong?

Thanks,
Sandro

**Comment by sawittwer** [comment]
I solved the problem by setting the zIndex option again during 'unspiderfy' events.

**Comment by msqsoft** [comment]
Hi sawittwer,

Request you to share sample code for it.

**Comment by sawittwer** [comment]
Since the zIndex option seems to be reset during spiderfying a added a new one called mIndex that is preserved:
`
oms.addListener('unspiderfy', function(markers) {
            markers.forEach(function(marker) {
                        marker.setOptions({
                                    zIndex: marker.mIndex
                        });
            });
});
`

**Comment by msqsoft** [comment]
Thanks a lot Bro. Appreciate your help and support.
