### ISSUE TITLE
ReferenceError on Safari, Firefox

### ISSUE THREAD

**Issue by chudobalukas** [jawj/OverlappingMarkerSpiderfier#124]
Hello,  
your library works fine on Chrome, IE. But on Safari, Firefox it doesnt works.  
Problem is when I call OverlappingMarkerSpiderfier function like 

**_oms = new OverlappingMarkerSpiderfier(map, { markersWontMove: true, markersWontHide: true });_**

Error
_ReferenceError: OverlappingMarkerSpiderfier is not defined_
on 
_oms.min.js column 10_

Can you help me with this issue? Thanks

**Comment by jawj** [comment]
How and where are you loading both the GMaps JS and the OMS JS? Could be a problem with script loading order, especially if using any defer/async scripts.

**Comment by chudobalukas** [comment]
I am loading this js as follow (first GMaps JS and second OMS JS):
<script async defer src="https://maps.googleapis.com/maps/api/js?&libraries=places&sensor=false&key=MY_KEY"></script>
<script defer src="http://jawj.github.io/OverlappingMarkerSpiderfier/bin/oms.min.js"></script>

**Comment by jawj** [comment]
Right — async loading is not going to work here. I'll be providing support for async loading in an update in the next few weeks.

In the meantime, the simplest fix is just to remove the `async` and `defer` attributes from both `script` tags, and make sure the script where you call `new OverlappingMarkerSpiderfier` comes after both of them.

**Comment by chudobalukas** [comment]
ok thanks, now it works 👍
