### ISSUE TITLE
Working with GeoJSON

### ISSUE THREAD

**Issue by ChrisTitos** [jawj/OverlappingMarkerSpiderfier#130]
Hi,

I use GeoJSON to add markers to my map via the [Data Layer](https://developers.google.com/maps/documentation/javascript/datalayer#load_geojson). This means I never call addMarker/removeMarker manually.

Is is still possible to use this library (which is exactly what I was looking for) in this use case?

**Comment by jawj** [comment]
I have not used GeoJSON or the Data Layer. A brief skim of those docs does not look promising. But I don't imagine it would be that hard to recreate that functionality yourself, integrating the addMarker/removeMarker calls?
