### ISSUE TITLE
Using mouseover instead of click

### ISSUE THREAD

**Issue by alexbrand** [jawj/OverlappingMarkerSpiderfier#14]
I tried using mouseover instead of click event to open markers, but it doesn't seem to work:

From the demo:

```
      oms.addListener('mouseover', function(marker) {
        iw.setContent(marker.desc);
        iw.open(map, marker);
     });
```

**Comment by mostafaAabed** [comment]
+1
but i want to spiderfy the marker on mouseover without dispatching the click event and it's punch of listeners
