### ISSUE TITLE
How to disable dragging colored marker.

### ISSUE THREAD

**Issue by gezaak** [jawj/OverlappingMarkerSpiderfier#144]
Hello,
i use this map https://github.com/jawj/OverlappingMarkerSpiderfier/blob/gh-pages/demo-3.html and i hope remove dragging marker.
Thanks for help.

**Comment by abrigard** [comment]
Hi. Could you solve it? I have the same issue.

**Comment by jawj** [comment]
Delete line 63, `draggable: true,`.
