### ISSUE TITLE
z-indexing and leg/image locations

### ISSUE THREAD

**Issue by hinch** [jawj/OverlappingMarkerSpiderfier#15]
I have 2 small issues and can't seem to resolve them.

z-index construct overriding seems to be being ignored.
I'm overriding the z's on construct using the following bit of code.
<code>
 var oms = new OverlappingMarkerSpiderfier(map,{
      markersWontMove: true, 
      markersWontHide: true, 
      nearbyDistance: 20, 
      legWeight: 3, 
      circleFootSeparation: 35,
      spiralFootSeparation: 35,
      usualLegZIndex: 100001,
      spiderfiedZIndex: 100000,
      highlightedLegZIndex: 100002
      });
</code>

The 2nd issue is I'm using custom icons and sizes different than the standard google ones.  This results in the images being out of line with the leg endings.  I can't seem to reposition the image in relation to the leg ending in any way.  Am I missing something?

Both issues can be seen in this little screenshot
http://i.imgur.com/gCkZS.png

**Comment by magicmb** [comment]
> That's right -- but you shouldn't need getMarkers(). Your spiderfy listener function receives two arrays: the first contains all spiderfied markers, and the second all unspiderfied ones. So you just need something like this:
> 
> ```
> oms.addListener('spiderfy', function(spiderfiedMarkers, unspiderfiedMarkers) {
>   for (var i = 0, len = unspiderfiedMarkers.length; i < len; i ++) {
>     marker = unspiderfiedMarkers[i];
>     // make marker transparent
>   }
> });
> ```

 🎉 Wow! That really does provide the icing on the cake as far as our OMS implementation goes (OMS-Leaflet). 

I didn't pick up on this either, but skimming the docs again it clearly states: `One use for these listeners is to make some distinction between spiderfied and non-spiderfied markers when some markers are spiderfied — e.g. highlighting those that are spiderfied, or dimming out those that aren’t.`

This would have been a fabulous example to include as part of the documentation, but even so it just goes to show what gems one can pick up on reading some of these old issue threads.

Again great work on this absolutely fabulous little plugin. ❤️ it!
