### ISSUE TITLE
Line representing the spiderfied marker not updated on marker movement

### ISSUE THREAD

**Issue by haider-ali** [jawj/OverlappingMarkerSpiderfier#165]
I am using firebase to get tracking information and update the marker location but when marker that is spiderfied changes its location marker is updated but the line  doesn't

**Comment by wwwizzarrdry** [comment]
Isn't this mentioned in the docs? I think you need to call Unspiderify and then Spiderify again when you make changes to the underlying OMS.

**Comment by jawj** [comment]
Not sure it is mentioned in the docs, but yes, I think if you're changing marker locations you may have to unspiderfy first.
