### ISSUE TITLE
Marker lines don't originate from the same point

### ISSUE THREAD

**Issue by kwebster16** [jawj/OverlappingMarkerSpiderfier#169]
Just wondering if there's anything I'm missing.

I'm assuming that the lines are pointing to the actual locations of the markers when they're spiderified.  But I find it looks a little odd, and I'm often getting lines that are originating a pixel or two off at the default zoom level of my map.

Is there a way to have them all originate out from a central location?

**Comment by jawj** [comment]
This is by design: each line emanates from the original location of its marker. I suppose if you wanted to you could calculate the average location and have them all start there, but it's not a change I'm inclined to make in general, since it is extra effort for a more misleading display.
