### ISSUE TITLE
How to keep spider markers showing after clicking away

### ISSUE THREAD

**Issue by aharpervc** [jawj/OverlappingMarkerSpiderfier#178]
Hello & thanks for this library, it's a great improvement on the default maps/cluster behavior.

I'm curious how I can keep the spidering "open" even when clicking away from a marker. Currently when clicking a spiderfied marker (or clicking away from the markers onto the map) the spiderfication will "close" back to a single marker. I'd prefer it stay spiderfied (and ideally be spiderfied by default rather than than clicking to open).

I'm unsure how to do that. Thoughts?

**Comment by aharpervc** [comment]
Of course right when I post this question I see this in the readme... 🤦‍♂️

> keepSpiderfied (default: false)

& 

> ignoreMapClick (default: false)

So maybe my only remaining question is about pre-opening the spiderfications?

**Comment by jawj** [comment]
> So maybe my only remaining question is about pre-opening the spiderfications?

This is a much-requested feature (see issue #2), but unfortunately the way the library works means it's not really possible.

**Comment by aharpervc** [comment]
Gotcha. Thanks for clarifying! Not being able to pre-open isn't a dealbreaker anyway.
