### ISSUE TITLE
TypeError: google.maps.__gjsload__ is not a function

### ISSUE THREAD

**Issue by cerw** [jawj/OverlappingMarkerSpiderfier#28]
I can not load your library after creating map i get error from google JS?

**Comment by mestefanell** [comment]
Hi, which api version did you used to solve the problem, i`m having the same issue with api 3

**Comment by cerw** [comment]
@mestefanell Hi I think I did this and that fixed it

    <script type="text/javascript">function load_google_map_api(){google.load("maps","3",{"other_params":"language=en&sensor=true&signed_in=true&libraries=places"});};</script>
    <script type="text/javascript" src="//www.google.com/jsapi?callback=load_google_map_api"></script>
