### ISSUE TITLE
Show count of markers spiderfied

### ISSUE THREAD

**Issue by markusmo** [jawj/OverlappingMarkerSpiderfier#30]
Hello
We are using your script on our site and now we are wondering, if it is possible to add a flag, when initializing the OMS to show the count of markers spiderfied on a certain point, like marker clusterer does. We have a lot of markers, who are directly above eachother and one does not know, if they are spiderfied or not. Would be a nice to have :-D

**Comment by geo1004** [comment]
It fits quite well with the clustering library and you can trigger the spiderfication by simulating a click on a cluster member:

1°) Simply add markers to oms, then in the cluster

```coffeescript
oms.addMarker(marker)

markerClusterer =
      new MarkerClusterer(
        window.map,
        markers,
        {
          zoomOnClick: false
          maxZoom: 12
          gridSize: 50
          styles: [
            url: "<%= asset_path('marker_gmap.png')%>"
            width: 42
            height: 56
            anchor: [13, 0]
            textSize: 12
            textColor: '#FFFFFF'
          ]
        }
      )
```

2°) Onclick on the cluster, zoom to make the spider element visible and loop through your oms markers collection and the cluster collection. If there is a match, trigger a click on that marker in the setTimeOut to let the time to the zoom

```coffeescript
google.maps.event.addListener markerClusterer, 'clusterclick', (cluster) ->
      markers = jQuery.extend(true, {}, cluster.getMarkers())
      marker = markers[0]
      break_loop = false
      window.map.setZoom(16)
      window.map.setCenter(cluster.getCenter())
      setTimeout (->
        jQuery.each markers, (index)->
          original_marker = markers[index]

          for i in [0..oms.getMarkers().length]
            continue unless oms.getMarkers()[i]?
            spider_marker = oms.getMarkers()[i]
            if original_marker['title'] == spider_marker['title']
              google.maps.event.trigger(spider_marker, 'click')
              break_loop = true
            break if break_loop == true
        return false if break_loop == true
      ), 500
```
3°) Listen for the unspiderfy event and zoom out to show clusters number and do whatever you want (here I close the infowindow)
```coffeescript
oms.addListener 'unspiderfy', (marker, event) ->
        infowindow.close()
        window.map.setZoom(12)
```

**Comment by MatrixOfDeath** [comment]
Hey could you copy correctly your codes it seems things are missing, i'm using oms v3 and markercluster v3, and also jquery.storelocator.js

that would be great :)
