### ISSUE TITLE
Spiderfy All?

### ISSUE THREAD

**Issue by georgecoltart** [jawj/OverlappingMarkerSpiderfier#49]
Hey there, thanks a lot of developing this it's a great plugin. 

I'm not sure if you'd thought of this use case, but I'm hoping to use this in a printing scenario, whereby the print view of a map would be much better suited for all markers to be spiderfied rather than having lots of them overlapping. 

Is there an easy way I can 'spiderfy all'? is it worth me trying to hack this together or is the underlying code such that this wont be possible without a lot of work? My JS skills are average and the source is a little scary :)

thanks again. 
George

**Comment by tiberakis** [comment]
Would it be possible to have spiderfying happen in response to a mouseover (not only a click) on a specific marker? Or, like in google earth, changing the shape of the pointer, so to warn the user that there is something underneath? Thank you.
