### ISSUE TITLE
InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama

### ISSUE THREAD

**Issue by latelier** [jawj/OverlappingMarkerSpiderfier#86]
I'm trying to use OverlappingMarkerSpiderfier and Gmaps(https://github.com/hpneo/gmaps) together but when I'm creating the instance of OverlappingMarkerSpiderfier I get this error :

**InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama**

I'm giving the google.maps.Map from my Gmaps map as the options like this :

```
 var map = new GMaps({
                    el: '#map-canvas',
                    lat: 22.945060,
                    lng: 10.701397,
                    zoom: 2,
                    scrollwheel: false,
                    panControl: false,
                    streetViewControl: false,
                    minZoom: 2,
                    maxZoom: 10,
                    styles: stylesArray
});
```

var oms = new OverlappingMarkerSpiderfier(map.map);

Thanks for your help!

**Comment by aditya748** [comment]
did you solve this?

**Comment by khurana3192** [comment]
I am facing the same problem..

**Comment by mariohmol** [comment]
Same here!

**Comment by loximoz** [comment]
Im facing the same issue, anything for solve it ?

**Comment by Yedzinovich** [comment]
Great. People have problems, but issue was closed without any explanations.

**Comment by jawj** [comment]
It was closed by the person who opened it on the same day they opened it! The additional problems were reported later.

Are you having the same problem? If so, I'll reopen. I feel like the issue is probably with GMaps, but I may be able to have a look.

**Comment by Yedzinovich** [comment]
Thank you very much for your response. I think I was able to figure it out.
It was a silly things that I did not notice before.

Best,
Inna

**Comment by jawj** [comment]
Thanks Inna. Is it worth mentioning what the problem was here, in case it helps someone else in future?

**Comment by zillBoy** [comment]
So, any luck with the solution!
When I first open the Google map its works fine and then I go to some other screen and come back again it gives me initialize error! and my marker onClick does not work.

**Comment by rysep2** [comment]
> When I first open the Google map its works fine and then I go to some other screen and come back again it gives me initialize error! and my marker onClick does not work.

I had the same problem and only switching to another library (https://github.com/chancezeus/oms) solved the problem for me.
